#!/bin/sh
# Runs on the VPS, invoked by .github/workflows/deploy.yml with the image reference
# built for the deployed commit. Pins that image, restarts the stack, and only
# reports success once the app container is actually healthy.
#
# Safe to run by hand:  sh deploy/remote-deploy.sh ghcr.io/<owner>/project-pilot:sha-abc1234
set -eu

IMAGE="${1:?usage: remote-deploy.sh <image-ref>}"
STACK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$STACK_DIR"

# Shipped under its repo name so it cannot collide with the build-on-this-host
# compose.yaml; on the server it is *the* compose file. Absent on a manual re-run,
# where the previous deploy already renamed it.
if [ -f compose.prod.yaml ]; then
    mv -f compose.prod.yaml compose.yaml
fi
if [ ! -f compose.yaml ]; then
    echo "FATAL: $STACK_DIR/compose.yaml is missing — run the deploy workflow once to ship it." >&2
    exit 1
fi

# The workflow writes this from the PROJECT_PILOT_ENV secret before calling us, so a
# missing file means a hand-run or a failed write. Failing here beats a container that
# boots and then dies on a ConfigError; profile and CVs ride inside the image.
if [ ! -f .env ]; then
    echo "FATAL: $STACK_DIR/.env is missing — set the PROJECT_PILOT_ENV secret and re-run the deploy." >&2
    exit 1
fi

# Compose merges this over compose.yaml automatically, so a plain `docker compose up -d`
# on the server uses the same image this deploy pinned.
cat > compose.override.yaml <<EOF
# Generated by the deploy workflow — do not edit by hand.
# Rollback: put an earlier sha-* tag here and run 'docker compose up -d'.
services:
  app:
    image: ${IMAGE}
EOF

# `edge` is external, owned by the proxy stack. Compose aborts with a bare "network
# edge not found" if it is absent, so create it rather than fail a deploy on a host
# where the proxy has not been brought up yet.
if ! docker network inspect edge >/dev/null 2>&1; then
    echo "shared network 'edge' not found — creating it"
    docker network create edge >/dev/null
fi

# The image is a PUBLIC GHCR package: pull it anonymously and make sure no stale
# login token lingers in the VPS's shared Docker config first. An *expired* token
# (e.g. an old CI `docker login` with a short-lived GITHUB_TOKEN) makes the
# registry answer "denied" even for a public image; with no token it pulls fine.
# Never `docker login ghcr.io` on this VPS.
docker logout ghcr.io >/dev/null 2>&1 || true
docker compose pull
docker compose up -d --remove-orphans
docker image prune -f >/dev/null 2>&1 || true

# The entrypoint applies migrations before starting the daemon, and the healthcheck
# only passes once a scan has actually succeeded — so this waits out the first scan.
printf 'waiting for the app container to become healthy'
verdict=still_starting
attempt=0
while [ "$attempt" -lt 60 ]; do
    container="$(docker compose ps -q app)"
    if [ -z "$container" ]; then
        verdict="FATAL: no app container was created."
        break
    fi
    state="$(docker inspect -f '{{.State.Status}}' "$container")"
    health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container")"
    case "$state:$health" in
        running:healthy)
            echo
            echo "app is healthy on ${IMAGE}"
            exit 0
            ;;
        running:none)
            echo
            echo "app is running (no healthcheck defined) on ${IMAGE}"
            exit 0
            ;;
        running:unhealthy)
            verdict="FATAL: app container reports unhealthy."
            break
            ;;
        exited:* | dead:* | restarting:*)
            verdict="FATAL: app container is $state."
            break
            ;;
    esac
    printf '.'
    sleep 5
    attempt=$((attempt + 1))
done
echo

# Only evidence of breakage fails a deploy. A container still working through its
# first scan is not evidence: on an empty database the seed run fetches every
# listing's detail page with a politeness delay and can outlast this wait.
if [ "$verdict" = still_starting ]; then
    echo "app is running on ${IMAGE}, still inside its healthcheck start period."
    echo "The first scan on an empty database takes a while. Watch it with:"
    echo "  cd $STACK_DIR && docker compose ps && docker compose logs -f app"
    exit 0
fi

echo "$verdict" >&2
echo "--- last 80 log lines ---" >&2
docker compose logs --tail=80 app >&2 || true
exit 1
