#!/bin/sh
# Runs on the VPS, invoked by .github/workflows/deploy.yml with the image reference
# built for the deployed commit. Pins that image, restarts the stack, and only
# reports success once the app container is actually healthy.
#
# Safe to run by hand:  sh deploy/remote-deploy.sh ghcr.io/<owner>/project-pilot:sha-abc1234
set -eu

IMAGE="${1:?usage: remote-deploy.sh <image-ref>}"
STACK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$STACK_DIR"

# Shipped under its repo name so it cannot collide with the build-on-this-host
# compose.yaml; on the server it is *the* compose file. Absent on a manual re-run,
# where the previous deploy already renamed it.
if [ -f compose.prod.yaml ]; then
    mv -f compose.prod.yaml compose.yaml
fi
if [ ! -f compose.yaml ]; then
    echo "FATAL: $STACK_DIR/compose.yaml is missing — run the deploy workflow once to ship it." >&2
    exit 1
fi

# The three things git deliberately does not carry. Failing here beats a container
# that boots and then dies on a ConfigError.
if [ ! -f .env ]; then
    echo "FATAL: $STACK_DIR/.env is missing — copy .env.example there and fill it in." >&2
    exit 1
fi
if [ ! -f profile/profile.md ]; then
    echo "FATAL: $STACK_DIR/profile/profile.md is missing — it is gitignored and must live on the server." >&2
    exit 1
fi
mkdir -p cv

# Compose merges this over compose.yaml automatically, so a plain `docker compose up -d`
# on the server uses the same image this deploy pinned.
cat > compose.override.yaml <<EOF
# Generated by the deploy workflow — do not edit by hand.
# Rollback: put an earlier sha-* tag here and run 'docker compose up -d'.
services:
  app:
    image: ${IMAGE}
EOF

docker compose pull
docker compose up -d --remove-orphans
docker image prune -f >/dev/null 2>&1 || true

# The entrypoint applies migrations before starting the daemon, and the healthcheck
# only passes once a scan has actually succeeded — so this waits out the first scan.
printf 'waiting for the app container to become healthy'
attempt=0
while [ "$attempt" -lt 60 ]; do
    container="$(docker compose ps -q app)"
    if [ -z "$container" ]; then
        echo
        echo "FATAL: no app container was created." >&2
        break
    fi
    state="$(docker inspect -f '{{.State.Status}}' "$container")"
    health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$container")"
    case "$state:$health" in
        running:healthy)
            echo
            echo "app is healthy on ${IMAGE}"
            exit 0
            ;;
        running:none)
            echo
            echo "app is running (no healthcheck defined) on ${IMAGE}"
            exit 0
            ;;
        running:unhealthy)
            echo
            echo "FATAL: app container reports unhealthy." >&2
            break
            ;;
        exited:* | dead:*)
            echo
            echo "FATAL: app container is $state." >&2
            break
            ;;
    esac
    printf '.'
    sleep 5
    attempt=$((attempt + 1))
done

echo
echo "--- last 80 log lines ---" >&2
docker compose logs --tail=80 app >&2 || true
exit 1
