"""Render the app's ``.env`` from the deploy environment's secrets and variables.

Every secret and variable configured for the workflow becomes one ``KEY=value`` line,
except the handful that configure the deploy itself. Nothing is hardcoded here, so
adding a setting later is a new secret in the ``prod`` environment and never a
workflow change.

The file goes to stdout so the workflow can pipe it straight into ``ssh``: values
never reach the job log. Only counts and key names are ever printed to stderr.
"""

import json
import os
import re
import sys

# These configure the deploy, not the app, so they must not land in the app's .env.
DEPLOY_ONLY = re.compile(r"^(VPS_.*|GITHUB_TOKEN)$", re.IGNORECASE)
VALID_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# The routine fire endpoint, as the API trigger's modal hands it out.
FIRE_URL_RE = re.compile(
    r"^https://api\.anthropic\.com/v1/claude_code/routines/[A-Za-z0-9_-]+/fire/?$"
)

# Without these the container dies at boot (see project_pilot.cli._build_pipeline and
# Pipeline.run_once), so failing here beats debugging a crash loop over SSH.
REQUIRED = (
    "OPENAI_API_KEY",
    "LLM_MODEL",
    "SEARCH_URLS",
    # The match-thread routine is THE notification channel; without it the daemon
    # aborts at boot by design, so the deploy refuses here instead.
    "CLAUDE_ROUTINE_FIRE_URL",
    "CLAUDE_ROUTINE_TOKEN",
    # The MCP service refuses to start without its bearer token.
    "MCP_TOKEN",
    # The reverse proxy's Docker network. Wrong or unset, the MCP container comes
    # up healthy and stays unreachable — a 502 with nothing in its own logs, which
    # is exactly the kind of silent failure this gate exists to prevent.
    "PROXY_NETWORK",
)

# The app starts without these, but not usefully: no contact mail, or a default password.
RECOMMENDED = (
    "CONTACT_MAIL",
    "POSTGRES_PASSWORD",
)


def _load(variable: str) -> dict[str, str]:
    """Parse one ``toJSON()`` blob into plain strings, ignoring anything malformed."""
    parsed: object = json.loads(os.environ.get(variable) or "{}")
    if not isinstance(parsed, dict):
        return {}
    return {str(key): str(value) for key, value in parsed.items()}


def collect() -> dict[str, str]:
    """Merge variables and secrets into the app's settings; secrets win on a clash."""
    merged: dict[str, str] = {}
    for blob in ("VARS_JSON", "SECRETS_JSON"):
        for key, value in _load(blob).items():
            if not DEPLOY_ONLY.match(key):
                merged[key] = value
    return merged


def problems(settings: dict[str, str]) -> list[str]:
    """Reasons the rendered file would not yield a working container.

    Values are checked for shapes a ``.env`` cannot carry unambiguously. Rejecting
    them loudly beats writing a file that a dotenv reader silently truncates.
    """
    found = [f"{key} is not set" for key in REQUIRED if not settings.get(key)]
    for key, value in sorted(settings.items()):
        if not VALID_NAME.match(key):
            found.append(f"{key!r} is not a usable environment variable name")
        elif "\n" in value or "\r" in value:
            found.append(f"{key} spans several lines, which a .env cannot represent")
        elif value != value.strip():
            found.append(f"{key} has leading or trailing whitespace")
        elif " #" in value:
            found.append(f"{key} contains ' #', which dotenv readers cut off as a comment")
    found.extend(_fire_url_problems(settings.get("CLAUDE_ROUTINE_FIRE_URL", "")))
    return found


def _fire_url_problems(url: str) -> list[str]:
    """Catch the routine's *page* URL being stored instead of its fire endpoint.

    Both are shown in the Claude UI and only one of them fires anything; the wrong
    one answers 403 at the first real match, hours after a deploy that looked
    perfectly healthy. The shape is fixed, so check it here rather than discover it
    from a warning session that cannot be sent either.
    """
    if not url:
        return []  # absence is already reported by the REQUIRED check
    if not FIRE_URL_RE.match(url):
        return [
            f"CLAUDE_ROUTINE_FIRE_URL is {url!r}, which is not a routine fire endpoint. "
            "Expected https://api.anthropic.com/v1/claude_code/routines/trig_.../fire "
            "— a https://claude.ai/code/routines/... address is the page, not the API."
        ]
    return []


def main() -> int:
    settings = collect()

    found = problems(settings)
    if found:
        for problem in found:
            print(f"::error::{problem}", file=sys.stderr)
        return 1

    for key in RECOMMENDED:
        if not settings.get(key):
            print(f"::warning::{key} is not set in the prod environment", file=sys.stderr)

    body = "".join(f"{key}={settings[key]}\n" for key in sorted(settings))
    sys.stdout.write("# Generated by the deploy workflow — edits here are overwritten.\n")
    sys.stdout.write(body)

    print(f"rendered {len(settings)} settings", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
